language: c
  
matrix:
  include:
    - name: "OSX - GCC"
      os: osx
      compiler: gcc
    - name: "OSX - CLANG"
      os: osx
      compiler: clang
    - name: "Linux - GCC"
      os: linux
      dist: xenial
      sudo: yes
      compiler: gcc
    - name: "Linux - CLANG"
      os: linux
      dist: xenial
      sudo: yes
      compiler: clang
    - name: "Windows - GCC"
      os: windows
      compiler: gcc
    - name: "Windows - CLANG"
      os: windows
      compiler: clang
  
# Build scripts
# The same on all platforms
script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then mingw32-make -k; fi
  - make -k
