language:
  - c

matrix:
  include:
    - name: "OSX Unit test"
      os: osx
      compiler:
        gcc
        clang
      before_install:
        brew update
        brew install ninja
        pip3 install meson
    - name: "Linux Unit test"
      os: linux
      dist: trusty
      sudo: yes
      python: 3.6
      compiler:
        gcc
        clang
      before_install:
        wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        pip3 install meson
  
# before_install:
#   - export PATH="$(pwd)/build:${PATH}"
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install meson; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update -q; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3.7; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3-pip; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install --upgrade pip; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install meson --user; fi

# Build scripts
# The same on all platforms
script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
  - ls builddir
