language:
  - c

compiler: gcc
  
matrix:
  include:
    - name: "OSX Unit test"
      os: osx
    - name: "Linux Unit test"
      os: linux
      dist: trusty
      sudo: yes
      before_install:
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      
before_install:
  - export PATH="$(pwd)/build:${PATH}"
  - brew update
  - brew install ninja
  - brew install meson
  
# Build scripts
# The same on all platforms
script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
  - ls builddir
