language: python
python: 3.7
os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang

before_install:
  - pip3 install --upgrade pip
  - pip3 install meson --user
  
# Build scripts
# The same on all platforms
script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
  - ls builddir
