language: c
  
matrix:
  include:
    - name: "OSX Unit test"
      os: osx
      compiler:
        - gcc
        - clang
      before_install:
        - export PATH="$(pwd)/build:${PATH}"
        - brew update
        - brew install ninja
        - brew install meson
    - name: "Linux Unit test"
      os: linux
      dist: trusty
      sudo: yes
      compiler:
        - gcc
        - clang
      before_install:
        - export PATH="$(pwd)/build:${PATH}"
        - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        - brew update
        - brew install ninja
        - brew install meson
  
# Build scripts
# The same on all platforms
script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
  - ls builddir
