language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      python: 3.7
      compiler: gcc
    - os: osx
      python: 3.7
      sudo: true
      compiler: gcc

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

install:
  - export PATH="$(pwd)/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - pip3 install --upgrade pip
  - pip3 install meson --user

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test