language: c
  
matrix:
  include:
    - name: "OSX - GCC"
      os: osx
      compiler: gcc
    - name: "OSX - CLANG"
      os: osx
      compiler: clang
    - name: "Linux - GCC"
      os: linux
      dist: trusty
      python: 3.7
      sudo: yes
      compiler: gcc
    - name: "Linux - CLANG"
      os: linux
      dist: trusty
      python: 3.7
      sudo: yes
      compiler: clang
    - name: "Windows - GCC"
      os: windows
      compiler: gcc
    - name: "Windows - CLANG"
      os: windows
      compiler: clang

before_install:
  # Install Python on Windows
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install -y python; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmd.exe /c "call RefreshEnv.cmd"; fi
  # Export PATH on OSX and Linux
  # TODO: Do we need this part?
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then export PATH="$(pwd)/build:${PATH}"; fi
  # Install Ninja
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt update && sudo apt install python3 python3-pip python3-setuptools python3-wheel ninja-build -y
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then alias python=python3; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install --user meson; fi
  # Download Meson both systems
  - git clone https://github.com/mesonbuild/meson
  
# Build scripts
# The same on all platforms
script:
  # Run meson
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then py meson/meson.py builddir; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./meson/meson.py builddir; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then meson builddir; fi
  # Run Ninja
  - ninja -C builddir
  - ls builddir

test_script:
  - ninja -C builddir test
