language:
  - c

compiler: gcc
  
matrix:
  include:
    - name: "OSX Unit test"
      os: osx
      before_install:
        - export PATH="$(pwd)/build:${PATH}"
        - brew update
        - brew install ninja
        - brew install meson
        
  
# Build scripts
# The same on all platforms
script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
  - ls builddir
